### ISSUE TITLE
Forge Version?

### ISSUE THREAD

**Issue by hyfabi** [capthehacker99/AutoLectern#20]
Hello, i would like to have the mod on Forge too. 

I dont know you are currently working on it but i want to try porting it in a fork.

**Comment by capthehacker99** [comment]
I won't work on a Forge mod for this because Forge sends the mod list to the server which means server admins would know whether this mod is used or not which I don't really like. https://wiki.vg/Minecraft_Forge_Handshake#ModList  

You can fork this and port it if you like as long as you follow the license.
